---
title: Myanmar Railways
timezone: UTC
collections:
  homepage-articles:
    title: Homepage Articles
    output: true
  posts:
    title: News
    output: true
  uploads:
    title: Uploads
    output: true
email: info@myanmar-railways.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
